language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gdal-bin

install:
  - pip install -r requirements.txt
script:
  - python tests.py
